import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { createContext } from "vm";

export const lightLGC = localFont({
  src: "../fonts/Louis George Cafe Light.ttf",
});
export const regularMonomakh = localFont({
  src: "../fonts/Monomakh-Regular.ttf",
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export type MessageContextType = {
  email: string;
  setEmail: (email: string) => void;
  message: string;
  setMessage: (message: string) => void;
};

export const MessageContext = createContext({} as MessageContextType);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${regularMonomakh.className} ${lightLGC.className} bg-[#8e5b36] antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
